# Generated by Django 6.0.2 on 2026-02-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='watch',
            field=models.ManyToManyField(null=True, to='pages.video'),
        ),
    ]
